# Generated by Django 3.2.9 on 2021-11-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='preciodistrib',
            field=models.IntegerField(default=0, verbose_name='Distribuidor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioferret',
            field=models.IntegerField(default=0, verbose_name='Ferreteria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='preciopubl',
            field=models.IntegerField(default=0, verbose_name='Publico'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
